### ISSUE TITLE
Readme shows cloud namespace which isn't available in 0.5.1

### ISSUE THREAD

**Issue by neilprosser** [mwmitchell/flux#10]
It took a little while for me to realise that the `flux.cloud` namespace was added after the current release. Is there any chance of that release being made? I'm keen to use Flux to connect to a SolrCloud cluster!

**Comment by mwmitchell** [comment]
Hi @neilprosser ! Yep, I can get this pushed out ASAP.

**Comment by mwmitchell** [comment]
@neilprosser - any chance you could test out tip of master?

**Comment by neilprosser** [comment]
Sure, I'll try and give this a go in the next couple of days.

**Comment by mwmitchell** [comment]
@neilprosser just tested the cloud/collection stuff out and looks good. I deployed version 0.6.0 to Clojars:

https://clojars.org/com.codesignals/flux/versions/0.6.0

**Comment by neilprosser** [comment]
Thanks for that. Sorry I didn't get round to it in the end. Had a busy week! Will be using the cloud stuff in an upcoming project soon though. Looking forward to it!
